### PR TITLE
Allow IComparable, IEquatable, and DayOfWeek.

### LINKED ISSUE #454: IComparable/IEquatable is not allowed
I tryed this code:
```cs
using System;

class Program
{
    static void Main()
    {
        ((IComparable<int>)0).CompareTo(1);
        ((IEquatable<int>)0).Equals(1);
    }
}
```
the exception I got was:
```
Unbreakable.AssemblyGuardException: Type System.IEquatable`1 is not allowed.

   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)

   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)

   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)

   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)

   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)

   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)

   at SharpLab.Server.Execution.Executor.Execute(CompilationStreamPair streams, IWorkSession session) in C:\projects\sharplab\source\Server\Execution\Executor.cs:line 72

   at SharpLab.Server.MirrorSharp.SlowUpdate.ProcessAsync(IWorkSession session, IList`1 diagnostics, CancellationToken cancellationToken) in C:\projects\sharplab\source\Server\MirrorSharp\SlowUpdate.cs:line 103

   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken)

   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken)

   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken)
```

I think these interfaces are safe.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
The first two fix ashmind/SharpLab#454.
And why prohibit DayOfWeek?

__Edit:__ I also saw `Span<T>` and its friends being prohibited. Can't we just prohibit its constructor that accepts a pointer?

### CODE REVIEW

**Comment by ashmind** [comment]
Thanks for your work! Unfortunately the Report file is auto-generated (which is why it bans `DayOfWeek` -- it actually just records that there is no rule for `DayOfWeek`, so it's disabled by default).

To fix the issue, you would need to change the policy itself, which is here:
https://github.com/ashmind/Unbreakable/blob/master/Policy/DefaultApiPolicyFactory.cs.

And yep I don't see any concern with allowing any of those interfaces. I could imagine a certain implementation being a problem, but classes are allowed/denied separately anyways.

**Comment by ashmind** [comment]
As for `Span` -- SharpLab has its own policy which allows `Span`, so it was not an immediate problem. But since pointer operations are already reasonably validated, I can't think of a way to abuse `Span`, so I wouldn't mind allowing it by default.

**Comment by teo-tsirpanis** [comment]
OK, I did it. Any help with generating a new policy report? I tried running the program with various arguments to no avail.

**Comment by ashmind** [comment]
No problem, I'll update it.

**Pull request merged**
